---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Commit via Netconf
      junos_config:
        src: "files/{{ environment_name }}/configs/{{ inventory_hostname }}.txt"
        src_format: text
        update: override
      when: junos_commit is defined
