---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    junos_build_dir: "{{ playbook_dir }}/build_dir"
  pre_tasks:
    - name: Remove host build temp directory
      file:
        path: "{{ junos_build_dir }}"
        state: absent
      changed_when: false
      check_mode: false  # run even in check mode, so we can see diffs
      run_once: true # no need to delete for all hosts

    - name: Create host build temp directory
      file:
        path: "{{ junos_build_dir }}"
        state: directory
      changed_when: false
      check_mode: false  # run even in check mode, so we can see diffs
      run_once: true # no need to delete for all hosts

    - name: Clone data repo for the enivornment
      git:
        repo: git@github.int.llabs.io:ig/data.junos-{{ environment_name }}.git
        dest: "{{ junos_build_dir }}/{{ environment_name }}"
        version: master
      changed_when: false
      check_mode: false # run even in check mode
      run_once: true # no need to checkout again for each host

    - block:
      - name: Chassis cluster information
        junos_command:
          commands: show chassis cluster status redundancy-group 0
          display: text
        register: result
        vars:
          ansible_connection: network_cli

      - set_fact:
          is_secondary: true
        when: "node == result.stdout | re_for_redundancy_group(false)"
      when: "'core-routers' in group_names"

  tasks:
    - name: Commit via Netconf
      junos_config:
        src: "{{ junos_build_dir }}/{{ environment_name }}/{{ inventory_hostname }}.txt"
        src_format: text
        update: override
      when: "junos_commit is defined and is_secondary|default(false) == false"
