---

# Generate and apply configuration to devices.
# Based loosely on https://github.com/dgjnpr/ansible-template-for-junos

# Clean up
- name: Remove and re-create build directories for each host
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: remove host build temp directory
      file: path={{ junos_build_dir }} state=absent
      check_mode: no  # run even in check mode, so we can see diffs
    - name: create host build temp directory
      file: path={{ junos_build_dir }} state=directory
      check_mode: no  # run even in check mode, so we can see diffs
    - name: remove host build temp directory
      file: path={{ junos_conf_file }} state=absent
      check_mode: no  # run even in check mode, so we can see diffs

# Template out configuration fragments, for common parts and device-specific parts
- name: Create SRX configuration fragments
  hosts: vsrx
  connection: local
  gather_facts: no
  roles:
    - common  # Common configuration
    - srx     # SRX-specifics

# Assemble parts and apply to devices
# The first task merges all the configuration fragments into one file.
# If merging the files results in a new file being created then a handler
# is triggered to push the configuration onto the device.
- name: Assemble and commit configuration
  hosts: all
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: assembling configurations
      assemble: src={{ junos_build_dir }} dest={{ junos_conf_file }}
      notify:
        - Commit configuration via NETCONF
        # - Pushing config ... please wait
      delegate_to: localhost
      check_mode: no  # run even in check mode, so we can see diffs

  handlers:

    - name: Commit configuration via NETCONF
      junos_install_config:
        host: "{{ junos_config_hostname }}"
        user: "{{ junos_config_user }}"  # This user's ssh key needs to be active
        file: "{{ junos_conf_file }}"
        overwrite: no
      delegate_to: localhost
      when: junos_commit is defined   # Use -e 'junos_commit=true' to run the commit
