---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    # The variaables are placed here as they are specific to the playbook and
    # would need to be replicated in every environment if placed in
    # group_vars/all.yml.  They are both needed in order to gather facts using
    # legacy junos-eznc python library.
    # https://docs.ansible.com/ansible/latest/modules/junos_facts_module.html
    ansible_python_interpreter: "/usr/bin/env python"
    junos_provider:
      host: "{{ inventory_hostname }}"
  tasks:
    - block:
      - name: Remove host build temp directory
        file:
          path: "{{ junos_build_dir }}"
          state: absent
        changed_when: false

      - name: Create host build temp directory
        file:
          path: "{{ junos_build_dir }}"
          state: directory
        changed_when: false

      - name: Clone data repo for the enivornment
        git:
          repo: git@github.int.llabs.io:ig/data.junos-{{ environment_name }}.git
          dest: "{{ junos_build_dir }}/{{ environment_name }}"
          version: master
        changed_when: false
      check_mode: false  # run even in check mode, so we can see diffs
      run_once: true # no need to delete for all hosts

    - block:
      - name: Gather 'junos_facts'
        junos_facts:
          provider: "{{ junos_provider }}"
          gather_subset:
            - "!default"
            - ofacts

      - set_fact:
          is_secondary: true
        when: "ansible_facts['srx_cluster_redundancy_group']['0'][node]\
               ['status'] == 'secondary'"
      when: "'core-routers' in group_names"

    - name: Commit via Netconf
      junos_config:
        src: "{{ junos_build_dir }}/{{ environment_name }}/{{ inventory_hostname }}.txt"
        src_format: text
        update: override
      when: "junos_commit is defined and is_secondary|default(false) == false"
