---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    # This variables is used to select which branch/tag is cloned for the data
    # repo.  The intent is for this is overriden at the command line to
    # reference a  specific tag or branch.  Master has been set here as a
    # fallback.
    data_repo_version: master
  tasks:
    - name: Set `static_config_dir` fact
      set_fact:
        static_config_dir: "{{ (local_config_source is defined)\
                            |ternary(local_config_source, junos_build_dir) }}"

    - name: Gather junos_facts
      junos_facts:
        provider: "{{ junos_provider }}"
        # `ofacts` collects the "old style" facts via the junos-eznc library
        # Additional information about `junos_facts` can be found at the  URL
        # below.
        gather_subset:
          - ofacts
      vars:
        # The variable placed here as it is specific to only this task and
        # would need to be replicated in every environment if placed in
        # group_vars/all.yml or the environment inventory.
        # https://docs.ansible.com/ansible/latest/modules/junos_facts_module.html
        junos_provider:
          host: "{{ inventory_hostname }}"
      delegate_to: localhost

    # Default to all hosts being primary, below we will change to false for
    # secondary SRX cluster nodes.
    - name: Set `is_configuration_target` to true
      set_fact:
        is_configuration_target: true

    - block:
        - name: "Set `is_configuration_target` to false for secondary node of \
          SRX cluster"
          set_fact:
            is_configuration_target: false
          when: "ansible_facts['srx_cluster_redundancy_group']['0'][node]\
                ['status'] == 'secondary'"
      when: ansible_facts['srx_cluster']

    - block:
        - name: Remove host build temp directory
          file:
            path: "{{ junos_build_dir }}"
            state: absent
          changed_when: false

        - name: Create host build temp directory
          file:
            path: "{{ junos_build_dir }}"
            state: directory
          changed_when: false

        - name: Clone {{ environment_name }} data repo, {{ data_repo_version }}
          git:
            repo: "git@github.int.llabs.io:ig/data.junos-{{ environment_name }}\
                   .git"
            dest: "{{ static_config_dir }}"
            version: "{{ data_repo_version }}"
          changed_when: false
      when: local_config_source is not defined
      check_mode: false  # run even in check mode, so we can see diffs
      run_once: true  # no need to delete for all hosts

    - name: Commit via Netconf
      junos_config:
        src: "{{ static_config_dir }}/{{ inventory_hostname }}.txt"
        src_format: text
        update: override
      # when `junos_commit` is true, and `is_configuration_target` is true
      when: junos_commit|default(false)|bool and is_configuration_target
